Repository oughtinc/mosaic, pull requests merged in 2019-07, with the labels that each got.

#630 style: graphQL->graphql standardization
  client/src/App.tsx
  client/src/auth/index.ts
  client/src/graphqlClient.ts
  client/src/pages/EpisodeShowPage/TimerAndTimeBudgetInfo/index.tsx
  server/test/lib/schema/index.spec.ts
  server/test/testHelpers/graphqlCalls.ts
Labels: Needs Review

#632 feat: autodeploy master on heroku
  README.md
Labels: Needs Review

#639 Small change to #638
  client/src/pages/EpisodeShowPage/WorkspaceRelations.ts
  client/src/pages/EpisodeShowPage/index.tsx
Labels: In-Review

#638 [WIP] Show link to original document in Experts workspace
  client/src/pages/EpisodeShowPage/index.tsx
Labels: WIP
